package authentication_project.fido.common.exception

class InvalidChallengeException(message:String):RuntimeException(message) {
}